[build]
  command = "npm run build"
  publish = "build"

[functions]
  # Sets a custom directory for Netlify Functions
  directory = "functions/"

  # Specifies `esbuild` for functions bundling
  node_bundler = "esbuild"

  included_files = ["functions/**"]